In [1]:
# import pandas
import pandas as pd

In [23]:
# read csv

df = pd.read_csv('./CSVS/bluepair.csv')

df2 = pd.read_csv('./CSVS/hardpair.csv')

df3 = pd.read_csv('./CSVS/semisortpairings.csv')

df4 = pd.read_csv('./CSVS/semihardpair1.csv')

df5 = pd.read_csv('./CSVS/semihardpair2.csv')

df6 = pd.read_csv('./CSVS/semihardpairing3.csv')

df7 = pd.read_csv('./CSVS/softcheese.csv')



df.head()

,Variety,Wines,Beverages,Fruits/Vegetables,Breads/Crackers,Condiments/Nuts,Meats/Fish
0,Blue Cheese,Dessert,Apple juice,Apples,Crusty bread,Black olives,Beef
1,Blue Cheese,Red,Coffee,Carrots,Nut bread,Honey,Fish
2,Blue Cheese,Sparkling,Gin,Celery,Whole grain crackers,Pecans,Ham
3,Blue Cheese,NaN,Lambic,Dried cranberries,NaN,NaN,Poultry
4,Blue Cheese,NaN,Pear nectar,Cucumbers,NaN,NaN,Shellfish
5,Blue Cheese,NaN,Stout,Pears,NaN,NaN,NaN
6,Blue Cheese,NaN,NaN,NaN,NaN,NaN,NaN
7,Creamy Blue,Dessert,Apple juice,Apricots (fresh or dried),Fruit bread,Almonds,Beef
8,Creamy Blue,Red,Coffee,Celery,Whole grain crackers,Black olives,Fish
9,Creamy Blue,Sparkling,Gin,Cucumbers,Water crackers,Dates,Ham
10,Creamy Blue,NaN,Lambic,Figs,NaN,NaN,Poultry
11,Creamy Blue,NaN,Pear nectar,Pears,NaN,NaN,Shellfish
12,Creamy Blue,NaN,Stout,NaN,NaN,NaN,NaN
13,Gorgonzola,Dessert,Apple juice,Apples,Crusty bread,Black olives,Beef
14,Gorgonzola,Red,Coffee,Bell peppers,Nut bread,Raisins,Fish
15,Gorgonzola,Sparkling,Gin,Carrots,Pumpernickel,Walnuts,Ham
16,Gorgonzola,NaN,Lambic,Citrus fruits,NaN,NaN,Poultry
17,Gorgonzola,NaN,Pear nectar,Dried cranberries,NaN,NaN,Shellfish
18,Gorgonzola,NaN,Stout,Tomatoes,NaN,NaN,NaN
19,Roquefort,Dessert,Apple juice,Apricots (fresh or dried),Crusty bread,Black olives,Beef
20,Roquefort,Red,Coffee,Apples,Whole grain crackers,Dates,Fish
21,Roquefort,Sparkling,Gin,Avocados,Water crackers,Roasted red peppers,Ham
22,Roquefort,NaN,Lambic,Celery,NaN,NaN,Poultry
23,Roquefort,NaN,Pear nectar,Cucumbers,NaN,,Shellfish
24,Roquefort,NaN,Stout,Grapes,NaN,NaN,NaN
25,Stilton,Dessert,Apple juice,Bell peppers,NaN,NaN,NaN
26,Stilton,Red,Coffee,Carrots,Nut bread,Honey,Beef
27,Stilton,Sparkling,Gin,Celery,Pumpernickel,Roasted red peppers,Fish
28,Stilton,NaN,Lambic,Dried cranberries,Wheat crackers,Pecans,Ham
29,Stilton,NaN,Pear nectar,Figs,NaN,NaN,Shellfish
30,Stilton,NaN,Stout,Pears,NaN,NaN,Poultry
31,Stilton,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
# check csv df2
df2.head()

,Variety,Wines,Beverages,Fruits/Vegetables,Breads/Crackers,Condiments/Nuts,Meats/Fish
0,Appenzeller,Fruity red,Bock,Apples,Raisin bread,Almonds,Ham
1,Appenzeller,White,Light beer,Carrots,Sourdough bread,Fruit butter,Poultry
2,Appenzeller,NaN,NaN,Cucumbers,Whole grain crackers,Pickles,Prosciutto
3,Appenzeller,NaN,NaN,Melons,NaN,NaN,Pork
4,Appenzeller,NaN,NaN,Strawberries,NaN,NaN,NaN

In [18]:
# check csv df3
df3.head()

,Variety,Wines,Beverages,Fruits/Vegetables,Breads/Crackers,Condiments/Nuts,Meats/Fish
0,Havarti,Fruity red,Pilsner,Carrots,Melba toast,Almonds,Poultry
1,Havarti,Light red,Stout,Cucumbers,Rye bread,Chutney,Seafood
2,Havarti,NaN,NaN,Dates,Water crackers,Roasted red peppers,Smoked turkey
3,Havarti,NaN,NaN,Pears,NaN,NaN,NaN
4,Havarti,NaN,NaN,Plums,NaN,NaN,NaN

In [19]:
# check csv df4
df4.head()

,Variety,Wines,Beverages,Fruits/Vegetables,Breads/Crackers,Condiments/Nuts,Meats/Fish
0,American,Fruity white,Apple juice,Apples,Pretzels,Mustard,Ham
1,American,Light red,White grape juice,Broccoli,Water crackers,Pickles,Bologna
2,American,NaN,NaN,Carrots,Wheat crackers,Raisins,Casseroles
3,American,NaN,NaN,Celery,NaN,NaN,NaN
4,American,NaN,NaN,Grapes,NaN,NaN,NaN

In [20]:
# check csv df5
df5.head()

,Variety,Wines,Beverages,Fruits/Vegetables,Breads/Crackers,Condiments/Nuts,Meats/Fish
0,Edam (mild),Fruity red,Lager,Carrots,Dark bread,Almonds,Beef
1,Edam (mild),Fruity white,Stout,Celery,Flatbread,Chutney,Cold cuts
2,Edam (mild),NaN,NaN,Cucumbers,Rye bread,Mustard,Ham
3,Edam (mild),NaN,NaN,Dried cranberries,Wheat crackers,NaN,Prosciutto
4,Edam (mild),NaN,NaN,Peaches,NaN,NaN,Pork

In [21]:
# check csv df6
df6.head()

,Variety,Wines,Beverages,Fruits/Vegetables,Breads/Crackers,Condiments/Nuts,Meats/Fish
0,Muenster,Fruity white,Cider,Apples,Dark bread,Chutney,Sausage
1,Muenster,Light red,Lager,Bell peppers,Nut bread,Mustard,Seafood
2,Muenster,Spicy white,Pilsner,Grapes,Wheat crackers,Pickles,Smoked turkey
3,Muenster,NaN,NaN,Pears,NaN,Walnuts,NaN
4,Muenster,NaN,NaN,Radishes,NaN,NaN,NaN

In [22]:
# check csv df7
df7.head()

,Variety,Wines,Beverages,Fruits/Vegetables,Breads/Crackers,Condiments/Nuts,Meats/Fish
0,Brie/Camembert,Fruity red,Cider,Apples,Crusty bread,Almonds,Beef
1,Brie/Camembert,Sparkling,White grape juice,Carrots,Melba toast,Chutney,Lamb
2,Brie/Camembert,NaN,Lambic-style beer,Dried fruit,Water table crackers,Sweet pickles,Seafood
3,Brie/Camembert,NaN,NaN,Mushrooms,NaN,NaN,Poultry
4,Brie/Camembert,NaN,NaN,Pears,NaN,NaN,NaN

In [27]:
# concat df and df2
concat_1 = pd.concat([df, df2])
concat_1

,Variety,Wines,Beverages,Fruits/Vegetables,Breads/Crackers,Condiments/Nuts,Meats/Fish,Wines,Beverages
0,Blue Cheese,Dessert,Apple juice,Apples,Crusty bread,Black olives,Beef,NaN,NaN
1,Blue Cheese,Red,Coffee,Carrots,Nut bread,Honey,Fish,NaN,NaN
2,Blue Cheese,Sparkling,Gin,Celery,Whole grain crackers,Pecans,Ham,NaN,NaN
3,Blue Cheese,NaN,Lambic,Dried cranberries,NaN,NaN,Poultry,NaN,NaN
4,Blue Cheese,NaN,Pear nectar,Cucumbers,NaN,NaN,Shellfish,NaN,NaN
...,...,...,...,...,...,...,...,...,...
25,Romano,NaN,NaN,Figs,Fruit bread,Pepperon-cini,Pork,NaN,Cider Apples
26,Romano,NaN,NaN,Pears,Rye bread,Honey,Ham,NaN,NaN
27,Romano,NaN,NaN,Tomatoes,NaN,NaN,Poultry,NaN,NaN
28,Romano,NaN,NaN,Zucchini dishes,NaN,NaN,Prosciutto,NaN,NaN
29,Romano,NaN,NaN,NaN,NaN,NaN,Salami,NaN,NaN

In [28]:
# concat df3 and df4
concat_2 = pd.concat([df3, df4])
concat_2

,Variety,Wines,Beverages,Fruits/Vegetables,Breads/Crackers,Condiments/Nuts,Meats/Fish
0,Havarti,Fruity red,Pilsner,Carrots,Melba toast,Almonds,Poultry
1,Havarti,Light red,Stout,Cucumbers,Rye bread,Chutney,Seafood
2,Havarti,NaN,NaN,Dates,Water crackers,Roasted red peppers,Smoked turkey
3,Havarti,NaN,NaN,Pears,NaN,NaN,NaN
4,Havarti,NaN,NaN,Plums,NaN,NaN,NaN
5,Havarti,NaN,NaN,Zucchini,NaN,NaN,NaN
6,Limburger,Brut sparkling,Bock,Apples,Dark bread,Mustard,Cold cuts
7,Limburger,White,India pale ale,Celery,Rye bread,Pickles,Kippered herring
8,Limburger,NaN,NaN,Onions,Pretzels,Walnuts,Sardines
9,Limburger,NaN,NaN,Pears,NaN,NaN,NaN
10,Monterey Jack,Aged red,Cran-raspberry juice,Apples,Melba toast,Cashews,Bratwurst
11,Monterey Jack,Fruity white,Lambic,Bell peppers,Pretzels,Mustard,Cold cuts
12,Monterey Jack,NaN,Tomato juice,Cherries Grapes,Pumpernickel,Pickles,Ham
13,Monterey Jack,NaN,NaN,Mushrooms,NaN,Raisins,Pastrami
14,Monterey Jack,NaN,NaN,Potato dishes,NaN,NaN,NaN
15,Mozzarella,Fruity red,Apple juice,Apples,Dark bread,Chutney,Sausage
16,Mozzarella,Fruity white,Cranberry juice,Bell peppers,Nut bread,Mustard,Seafood
17,Mozzarella,NaN,Hot or iced tea,Carrots,Wheat crackers,Pickles,Smoked turkey
18,Mozzarella,NaN,Pilsner,Grapes,NaN,Walnuts,NaN
19,Mozzarella,NaN,NaN,Melon,NaN,NaN,NaN
20,Mozzarella,NaN,NaN,Tomatoes,NaN,NaN,NaN
21,Port Salut,Fruity red,Amber ale,Apples,Rye bread,Fruit butter,Beef
22,Port Salut,Light red,NaN,Carrots,Whole grain bread,Mustard,Ham
23,Port Salut,NaN,NaN,Celery,Pumpernickel,Pecans,Sardines
24,Port Salut,NaN,NaN,Grapes,NaN,NaN,Pork
25,Port Salut,NaN,NaN,Plums,NaN,NaN,NaN
26,Port Salut,NaN,NaN,Zucchini,NaN,NaN,NaN
0,American,Fruity white,Apple juice,Apples,Pretzels,Mustard,Ham
1,American,Light red,White grape juice,Broccoli,Water crackers,Pickles,Bologna
2,American,NaN,NaN,Carrots,Wheat crackers,Raisins,Casseroles
3,American,NaN,NaN,Celery,NaN,NaN,NaN
4,American,NaN,NaN,Grapes,NaN,NaN,NaN
5,American,NaN,NaN,Pears,NaN,NaN,NaN
6,Baby Swiss,Aged red,Apple juice,Apples,Fruit bread,Cashews,Ham
7,Baby Swiss,Fruity white,Lager Stout,Celery,Water crackers,Fruit butter,Chicken
8,Baby Swiss,NaN,NaN,Grapes,Wheat crackers,Mustard,Corned beef
9,Baby Swiss,NaN,NaN,Mushrooms,NaN,NaN,NaN
10,Baby Swiss,NaN,NaN,Pears,NaN,NaN,NaN
11,Baby Swiss,NaN,NaN,Potato dishes,NaN,NaN,NaN
12,Cheddar,Dessert wines,Pale ale,Apples,Dark bread,Cashews,Beef
13,Cheddar,Red,Sparkling cider,Apricots (fresh/dried),Melba toast,Chutney,Bologna
14,Cheddar,NaN,Stout,Broccoli,Pretzels,Mustard,Ham
15,Cheddar,NaN,NaN,Cherries (fresh/dried),NaN,NaN,Smoked turkey
16,Cheddar,NaN,NaN,Red peppers,NaN,NaN,Summer sausage
17,Cheddar,NaN,NaN,Tomatoes,NaN,NaN,NaN
18,Colby/Colby Jack,Blush,Lager,Apples,Melba toast,Salsa,Beef
19,Colby/Colby Jack,Red,Pilsner,Grapes,Water crackers,Almonds,Bratwurst
20,Colby/Colby Jack,NaN,White grapefruit juice,Red peppers,Wheat crackers,Hot sweet mustard,Ham
21,Colby/Colby Jack,NaN,NaN,Strawberries,NaN,NaN,Summer sausage
22,Colby/Colby Jack,NaN,NaN,Tomatoes,NaN,NaN,Pork
23,Colby/Colby Jack,NaN,NaN,Melons,NaN,NaN,NaN
24,NaN,NaN,NaN,Onions,NaN,NaN,NaN

In [29]:
# concat df, df2, df3, df4
cc = pd.concat([concat_1, concat_2])
cc

,Variety,Wines,Beverages,Fruits/Vegetables,Breads/Crackers,Condiments/Nuts,Meats/Fish,Wines,Beverages
0,Blue Cheese,Dessert,Apple juice,Apples,Crusty bread,Black olives,Beef,NaN,NaN
1,Blue Cheese,Red,Coffee,Carrots,Nut bread,Honey,Fish,NaN,NaN
2,Blue Cheese,Sparkling,Gin,Celery,Whole grain crackers,Pecans,Ham,NaN,NaN
3,Blue Cheese,NaN,Lambic,Dried cranberries,NaN,NaN,Poultry,NaN,NaN
4,Blue Cheese,NaN,Pear nectar,Cucumbers,NaN,NaN,Shellfish,NaN,NaN
...,...,...,...,...,...,...,...,...,...
20,Colby/Colby Jack,NaN,NaN,Red peppers,Wheat crackers,Hot sweet mustard,Ham,NaN,White grapefruit juice
21,Colby/Colby Jack,NaN,NaN,Strawberries,NaN,NaN,Summer sausage,NaN,NaN
22,Colby/Colby Jack,NaN,NaN,Tomatoes,NaN,NaN,Pork,NaN,NaN
23,Colby/Colby Jack,NaN,NaN,Melons,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,Onions,NaN,NaN,NaN,NaN,NaN

In [30]:
# concat first four (cc) and df7
concat_3 = pd.concat([cc, df7])
concat_3

,Variety,Wines,Beverages,Fruits/Vegetables,Breads/Crackers,Condiments/Nuts,Meats/Fish,Wines,Beverages
0,Blue Cheese,Dessert,Apple juice,Apples,Crusty bread,Black olives,Beef,NaN,NaN
1,Blue Cheese,Red,Coffee,Carrots,Nut bread,Honey,Fish,NaN,NaN
2,Blue Cheese,Sparkling,Gin,Celery,Whole grain crackers,Pecans,Ham,NaN,NaN
3,Blue Cheese,NaN,Lambic,Dried cranberries,NaN,NaN,Poultry,NaN,NaN
4,Blue Cheese,NaN,Pear nectar,Cucumbers,NaN,NaN,Shellfish,NaN,NaN
...,...,...,...,...,...,...,...,...,...
24,Queso Fresco,NaN,NaN,Citrus fruits,Pita,Honey,Turkey,Sangria,NaN
25,Queso Fresco,NaN,NaN,Avocados,Tortillas,Salsa,NaN,NaN,NaN
26,Queso Fresco,NaN,NaN,Papayas,NaN,NaN,NaN,NaN,NaN
27,Queso Fresco,NaN,NaN,Mangos,NaN,NaN,NaN,NaN,NaN
28,Queso Fresco,NaN,NaN,Tomatoes,NaN,NaN,NaN,NaN,NaN

In [32]:
# concant df5 and df6
concat_4 = pd.concat([df5, df6])
concat_4.head()

,Variety,Wines,Beverages,Fruits/Vegetables,Breads/Crackers,Condiments/Nuts,Meats/Fish
0,Edam (mild),Fruity red,Lager,Carrots,Dark bread,Almonds,Beef
1,Edam (mild),Fruity white,Stout,Celery,Flatbread,Chutney,Cold cuts
2,Edam (mild),NaN,NaN,Cucumbers,Rye bread,Mustard,Ham
3,Edam (mild),NaN,NaN,Dried cranberries,Wheat crackers,NaN,Prosciutto
4,Edam (mild),NaN,NaN,Peaches,NaN,NaN,Pork

In [33]:
# concat all
final = pd.concat([concat_3, concat_4])
final

,Variety,Wines,Beverages,Fruits/Vegetables,Breads/Crackers,Condiments/Nuts,Meats/Fish,Wines,Beverages
0,Blue Cheese,Dessert,Apple juice,Apples,Crusty bread,Black olives,Beef,NaN,NaN
1,Blue Cheese,Red,Coffee,Carrots,Nut bread,Honey,Fish,NaN,NaN
2,Blue Cheese,Sparkling,Gin,Celery,Whole grain crackers,Pecans,Ham,NaN,NaN
3,Blue Cheese,NaN,Lambic,Dried cranberries,NaN,NaN,Poultry,NaN,NaN
4,Blue Cheese,NaN,Pear nectar,Cucumbers,NaN,NaN,Shellfish,NaN,NaN
...,...,...,...,...,...,...,...,...,...
13,Swiss,NaN,NaN,Bell peppers,Pretzels,Mustard,Cold cuts,Aged red,Lambic
14,Swiss,NaN,NaN,Cherries,Pumpernickel,Pickles,Ham,NaN,Tomato juice
15,Swiss,NaN,NaN,Mushrooms,NaN,Raisins,Pastrami,NaN,NaN
16,Swiss,NaN,NaN,Potato dishes,NaN,NaN,NaN,NaN,NaN
17,Swiss,NaN,NaN,Grapes,NaN,NaN,NaN,NaN,NaN

In [34]:
# turn into a CSV
final.to_csv('final_cheeseboard.csv', index=False)