In [1]:
# add dependencies

import pandas as pd
from sqlalchemy import create_engine

In [2]:
# sqlite path

database_path = "wine_db.sqlite"

In [3]:
# engine connect

engine = create_engine(f"sqlite:///{database_path}")
conn = engine.connect()

In [4]:
# read database wine

data_wine = pd.read_sql("SELECT * FROM wine", conn)
data_wine

,id,title,country,points,price,province,variety,winery
0,1,L'Arboc NV 1919 Brut SelecciÃƒÂ³ Sparkling (Cava),Spain,88,$13.00,Catalonia,Sparkling Blend,L'Arboc
1,2,Guidi 1929 2015 Vernaccia di San Gimignano,Italy,87,$14.00,Tuscany,Vernaccia,Guidi 1929
2,3,Poderi dal Nespoli 1929 2011 Prugneto (Sangiov...,Italy,84,$15.00,Central Italy,Sangiovese,Poderi dal Nespoli 1929
3,4,Adega Viuva Gomes 1934 Reserva Velho Red (Cola...,Portugal,93,$495.00,Colares,Ramisco,Adega Viuva Gomes
4,5,GÃƒÂ©rard Bertrand 1945 Legend Vintage Red (Ri...,France,95,$350.00,Languedoc-Roussillon,Red Blend,GÃƒÂ©rard Bertrand
...,...,...,...,...,...,...,...,...
49989,49990,Familie Zull 2016 Lust & Laune RosÃƒÂ© (Nieder...,Austria,88,$15.00,NiederÃƒÂ¶sterreich,RosÃƒÂ©,Familie Zull
49990,49991,JÃƒÂ¤ger 2016 Vorder Seiber Federspiel GrÃƒÂ¼n...,Austria,90,$25.00,Wachau,GrÃƒÂ¼ner Veltliner,JÃƒÂ¤ger
49991,49992,Zonin NV CuvÃƒÂ¨e 1821 Brut (Prosecco),Italy,86,$15.00,Veneto,Glera,Zonin
49992,49993,Osborne NV Pedro Ximenez 1827 Sweet Sherry She...,Spain,94,$14.00,Andalucia,Sherry,Osborne
49993,49994,CodornÃƒÂ­u NV Reserva CuvÃƒÂ©e Barcelona 1872...,Spain,85,None,Catalonia,Sparkling Blend,CodornÃƒÂ­u